/**
 * Regenerates src/levels/medals.ts (medal times per level and ride).
 * Run after changing physics or levels:  npx tsx scripts/dev/medals.ts
 */
import { writeFileSync } from 'node:fs';
import { LEVELS } from '../../src/levels/levels';
import { computeMedals, medalPairs } from '../../src/levels/medalTimes';

const rows: string[] = [];
for (const [level, v] of medalPairs(LEVELS)) {
  const m = computeMedals(level, v);
  if (m) rows.push(`  '${level.id}:${v.id}': [${m.join(', ')}],`);
  console.log(`${level.id}:${v.id}`.padEnd(28), m ? m.join(' / ') : 'no clean finish');
}
writeFileSync(
  new URL('../../src/levels/medals.ts', import.meta.url),
  `// Generated by scripts/dev/medals.ts: do not edit by hand.
import type { MedalTimes } from './medalTimes';

/** Bronze, silver, gold and dev finish times (s) per level and ride, on the home world. */
export const MEDAL_TIMES: Record<string, MedalTimes> = {
${rows.join('\n')}
};
`,
);
