/** Merges ridesolve.ts output files into src/levels/rideSolutions.ts (see ridesolveall.sh). */
import { readFileSync, writeFileSync } from 'node:fs';
import { RIDE_SOLUTIONS } from '../../src/levels/rideSolutions';

const all: Record<string, unknown> = { ...RIDE_SOLUTIONS };
for (const file of process.argv.slice(2)) {
  for (const line of readFileSync(file, 'utf8').split('\n')) {
    const [key, plan] = line.split('\t');
    if (key && plan) all[key] = JSON.parse(plan);
  }
}
const rows = Object.keys(all)
  .sort()
  .map((k) => `  '${k}': ${JSON.stringify(all[k]).replace(/,/g, ', ')},`);
writeFileSync(
  new URL('../../src/levels/rideSolutions.ts', import.meta.url),
  `// Generated by scripts/dev/ridesolveall.sh: do not edit by hand.
import type { InputPlan } from './ride';

/** Inputs that finish a level needing input on a ride its own solution doesn't fit (\`level:ride\`). */
export const RIDE_SOLUTIONS: Record<string, InputPlan> = {
${rows.join('\n')}
};
`,
);
console.log(`${rows.length} ride solutions`);
